services:
    - name: web
      buildCommand: 'composer install --optimize-autoloader --no-dev'
      startCommand: 'php artisan serve --host 0.0.0.0 --port $PORT'
      healthCheckPath: '/'

      env:
          - key: APP_ENV
            value: production
